### ISSUE TITLE
1.12.1?

### ISSUE THREAD

**Issue by princemorii** [Katrix-/PleaseWelcome#1] opened 2017-08-05 02:09 UTC
When will this be compatible with the latest build of SpongePoweredForge?

Thank you

**Comment by Katrix** [comment] 2017-08-31 09:57
Sorry for not getting back to this until now, been busy moving. 

Unsure what the issue is as I remember there being some problems with plugins loading in incorrect order on Sponge. That should be fixed in KatLib, but no version containing the fix has been released yet. As for 1.12 specifically, I'm wary releasing an official build until [this](https://github.com/SpongePowered/SpongeAPI/pull/1370) is merged. It it works, great, if it doesn't too bad.

Do note that whatever the issue is, I can't release a new version for another week or so once I get a new computer which I can do dev stuff.

**Comment by Katrix** [comment] 2017-09-24 20:04
A version that supports Sponge API 7.0.0 has been released. Should work fine.

**Closed as completed by Katrix** 2017-09-24 20:04 UTC
